package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer id;
	private Goods goods;
	private Orders orders;
	private Integer num;

	public Car() {
	}

	public Car(Goods goods, Orders orders, Integer num) {
		this.goods = goods;
		this.orders = orders;
		this.num = num;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

}
