package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private Integer id;
	private GoodsType goodsType;
	private Integer click;
	private String context;
	private String img;
	private Integer isT;
	private String name;
	private Integer num;
	private double price;
	private Integer status;
	private Date time;
	private Integer type;
	private Set<Car> cars = new HashSet<Car>(0);

	public Goods() {
	}

	public Goods(double price) {
		this.price = price;
	}

	public Goods(GoodsType goodsType, Integer click, String context,
			String img, Integer isT, String name, Integer num, double price,
			Integer status, Date time, Integer type, Set<Car> cars) {
		this.goodsType = goodsType;
		this.click = click;
		this.context = context;
		this.img = img;
		this.isT = isT;
		this.name = name;
		this.num = num;
		this.price = price;
		this.status = status;
		this.time = time;
		this.type = type;
		this.cars = cars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public GoodsType getGoodsType() {
		return this.goodsType;
	}

	public void setGoodsType(GoodsType goodsType) {
		this.goodsType = goodsType;
	}

	public Integer getClick() {
		return this.click;
	}

	public void setClick(Integer click) {
		this.click = click;
	}

	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Integer getIsT() {
		return this.isT;
	}

	public void setIsT(Integer isT) {
		this.isT = isT;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Set<Car> getCars() {
		return this.cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

}
