package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * GoodsType generated by hbm2java
 */
public class GoodsType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Goods> goodses = new HashSet<Goods>(0);

	public GoodsType() {
	}

	public GoodsType(String name, Set<Goods> goodses) {
		this.name = name;
		this.goodses = goodses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Goods> getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set<Goods> goodses) {
		this.goodses = goodses;
	}

}
