package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private Integer id;
	private String text;
	private Date time;

	public Notice() {
	}

	public Notice(String text, Date time) {
		this.text = text;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
