package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer id;
	private UserInfo userInfo;
	private double money;
	private Integer status;
	private Date time;
	private Set<Car> cars = new HashSet<Car>(0);

	public Orders() {
	}

	public Orders(double money) {
		this.money = money;
	}

	public Orders(UserInfo userInfo, double money, Integer status, Date time,
			Set<Car> cars) {
		this.userInfo = userInfo;
		this.money = money;
		this.status = status;
		this.time = time;
		this.cars = cars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Set<Car> getCars() {
		return this.cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

}
