package org.generator.demo;

// Generated 2016-9-5 22:56:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String address;
	private double money;
	private String nname;
	private String qq;
	private String uname;
	private String upass;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Money> moneys = new HashSet<Money>(0);

	public UserInfo() {
	}

	public UserInfo(double money) {
		this.money = money;
	}

	public UserInfo(String address, double money, String nname, String qq,
			String uname, String upass, Set<Orders> orderses, Set<Money> moneys) {
		this.address = address;
		this.money = money;
		this.nname = nname;
		this.qq = qq;
		this.uname = uname;
		this.upass = upass;
		this.orderses = orderses;
		this.moneys = moneys;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public String getNname() {
		return this.nname;
	}

	public void setNname(String nname) {
		this.nname = nname;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	public Set<Money> getMoneys() {
		return this.moneys;
	}

	public void setMoneys(Set<Money> moneys) {
		this.moneys = moneys;
	}

}
