package org.generator.demo;

// Generated 2016-9-5 22:59:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GoodsType generated by hbm2java
 */
@Entity
@Table(name = "goodstype", catalog = "smallshop")
public class GoodsType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Goods> goodses = new HashSet<Goods>(0);

	public GoodsType() {
	}

	public GoodsType(String name, Set<Goods> goodses) {
		this.name = name;
		this.goodses = goodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsType")
	public Set<Goods> getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set<Goods> goodses) {
		this.goodses = goodses;
	}

}
