package org.generator.demo;

// Generated 2016-9-5 22:59:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", catalog = "smallshop")
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String address;
	private double money;
	private String nname;
	private String qq;
	private String uname;
	private String upass;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Money> moneys = new HashSet<Money>(0);

	public UserInfo() {
	}

	public UserInfo(double money) {
		this.money = money;
	}

	public UserInfo(String address, double money, String nname, String qq,
			String uname, String upass, Set<Orders> orderses, Set<Money> moneys) {
		this.address = address;
		this.money = money;
		this.nname = nname;
		this.qq = qq;
		this.uname = uname;
		this.upass = upass;
		this.orderses = orderses;
		this.moneys = moneys;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "money", nullable = false, precision = 22, scale = 0)
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	@Column(name = "nname")
	public String getNname() {
		return this.nname;
	}

	public void setNname(String nname) {
		this.nname = nname;
	}

	@Column(name = "qq")
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "uname")
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "upass")
	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfo")
	public Set<Money> getMoneys() {
		return this.moneys;
	}

	public void setMoneys(Set<Money> moneys) {
		this.moneys = moneys;
	}

}
